
version: "3.3"

services:

  db:
    container_name: "db"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: flextock
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

  api:
    container_name: "fastapi"
    build: ./
    ports:
      - "3000:3000"
